config/routes.rb
EmailExtension::Engine.routes.draw do
  match 'settings' => 'settings#index'
  get 'email' => 'messages#email'
  
  resources :messages
  
  root :to => "settings#index"
end

app/models/anypresence_extension/account.rb
require AnypresenceExtension::Engine.root.join('app', 'models', 'anypresence_extension', 'account')

module AnypresenceExtension 
  class Account < ActiveRecord::Base
    include AnypresenceExtension::Common::AnypresenceClient
    
    attr_accessible :email_from
  
    has_many :email_options, :dependent => :destroy
    has_many :consume_email_options, :dependent => :destroy
    
    def get_fields
      field_names = []
      res = ap_client.metadata.fetch.to_json
      res.each do |x|
        fields = x["field_definitions"]
        fields.each do |f|
          h = {}
          h[:name] = f["name"]
          h[:_id] = f["_id"]
          field_names.push(h)
        end
      end
      field_names
    end
    
    # Finds the object definition name.
    def find_object_name(text)
      text.strip
    end
    
    def create_object_instance(consume_email_option, data)
      ap_client.data(consume_email_option.name)
      ap_client.create({:object_instance =>{consume_email_option.body_map => data}})
    end
  end
end

app/models/email_extension/account.rb
module EmailExtension 
  class Account
    include Mongoid::Document
    include Mongoid::Timestamps

    field :to_address, type: String
    field :from_address, type: String
    field :subject, type: String
    field :outgoing_message_format, type: String
    field :sendgrid_username, type: String
    field :sendgrid_password, type: String
    
    attr_accessible :to_address, :from_address, :subject, :outgoing_message_format, :sendgrid_username, :sendgrid_password
  
  end
end

app/models/email_extension/consume_email_option.rb
module EmailExtension
  class ConsumeEmailOption
    include Mongoid::Document
    include Mongoid::Timestamps
  end
end

app/models/email_extension/email_option.rb
module EmailExtension
  class EmailOption
    include Mongoid::Document
    include Mongoid::Timestamps
  end
end

app/models/email_extension/message.rb
require 'kaminari'

module EmailExtension
  class Message
    include Mongoid::Document
    include Mongoid::Timestamps
    
    paginates_per 10
  
    field :from, type: String
    field :to, type: String
    field :subject, type: String
    field :body, type: String
    
    validates_presence_of :from, :to
    
    attr_accessible :from, :to, :subject, :body
    
  end
end

app/models/email_extension/notifier.rb
module EmailExtension
  class Notifier < ActionMailer::Base

    def send_email(params, object_name, from_address, to_address, subject, body)
      account = EmailExtension::Account.first
      ActionMailer::Base.smtp_settings = {
        :user_name => account.sendgrid_username,
        :password => account.sendgrid_password,
        :port => 465,
        :domain => "anypresence.com",
        :address => "smtp.sendgrid.net",
        :authentication => :plain,
        :enable_starttls_auto => true,
        :ssl => true
      }
      ActionMailer::Base.delivery_method = :smtp

      formatted_body = ::EmailExtension::Common::LiquidTemplate.parse_format_string(body, object_name, params)
      formatted_from_address = ::EmailExtension::Common::LiquidTemplate.parse_format_string(from_address, object_name, params)
      formatted_to_address = ::EmailExtension::Common::LiquidTemplate.parse_format_string(to_address, object_name, params)
      formatted_subject = ::EmailExtension::Common::LiquidTemplate.parse_format_string(subject, object_name, params)

      message = mail(from: formatted_from_address, to: formatted_to_address, subject: formatted_subject, body: formatted_body)
      ::EmailExtension::Message.create(from: formatted_from_address, to: formatted_to_address, subject: formatted_subject, body: formatted_body)
      message
    end

  end
end

app/models/email_extension/setting.rb
module EmailExtension
  class Setting
  end
end

app/controllers/email_extension/application_controller.rb
class EmailExtension::ApplicationController < ApplicationController
    layout "layouts/admin"
    protect_from_forgery
end

app/controllers/email_extension/consume_email_options_controller.rb
module EmailExtension
  class ConsumeEmailOptionsController < ::EmailExtension::ApplicationController
    before_filter :find_available_objects, :except => [:index, :destroy]

    def index
      @consume_email_options = current_account.consume_email_options
    end
  
    def new
      @consume_email_option = current_account.consume_email_options.build
      consume_email_options = current_account.consume_email_options.all
      consume_email_options.each do |x|
        @available_objects.delete(x.name)
      end
    end
  
    def create
      @consume_email_option = current_account.consume_email_options.build(params[:consume_email_option])
    
      if @consume_email_option.save
        flash[:notice] = "Consume email option has been created."
        redirect_to [current_account, @consume_email_option]
      else
        flash[:alert] = "Consume email option has not been created."
        render "new"
      end
    end
  
    def edit
      @consume_email_option = EmailOption.find(params[:id])
    end  
  
    def update
      @consume_email_option =  EmailOption.find(params[:id])
      if @consume_email_option.update_attributes(params[:consume_email_option])
        flash[:notice] = "Consume email option has been updated."
        redirect_to [current_account, @consume_email_option]
      else
        flash[:alert] = "Consume email option has not been updated."
        render :action => "edit"
      end
    end
  
    def show
      @consume_email_option = ConsumeEmailOption.find(params[:id])
    end
  
    def destroy
      @consume_email_option = current_account.consume_email_options.find(params[:id])
      @consume_email_option.destroy
      flash[:notice] = "Consume email option has been deleted."
      redirect_to settings_path
    end
  end
end

app/controllers/email_extension/messages_controller.rb
require_dependency "email_extension/application_controller"

module EmailExtension
  class MessagesController < ApplicationController
    before_filter :authenticate_admin!
    
    def new
      @message = ::EmailExtension::Message.new
    end
    
    def create
      message = ::EmailExtension::Message.new(params[:message])
      status = false
      begin
        ::EmailExtension::Notifier.send_email(nil, nil, message.from, message.to, message.subject, message.body).deliver
        status = true
      rescue
        Rails.logger.error "Unable to send out email: #{$!.message}"
      end
      
      respond_to do |format|
        if status
          format.html { redirect_to settings_path }
        else
          format.html { render action: "new" }
        end
      end
    end
    
  end
end

app/controllers/email_extension/settings_controller.rb
require_dependency "email_extension/application_controller"
module EmailExtension
  class SettingsController < ApplicationController
    before_filter :authenticate_admin!
  
    def index
      @messages = ::EmailExtension::Message.all.page(params[:page])
    end
    
  end
end

app/helpers/email_extension/application_helper.rb
module EmailExtension
  module ApplicationHelper
  end
end

app/helpers/email_extension/consume_email_options_helper.rb
module EmailExtension
  module ConsumeEmailOptionsHelper
  end
end

app/helpers/email_extension/email_options_helper.rb
module EmailExtension
  module EmailOptionsHelper
  end
end

app/helpers/email_extension/messages_helper.rb
module EmailExtension
  module MessagesHelper
  end
end

app/helpers/email_extension/settings_helper.rb
module EmailExtension
  module SettingsHelper
  end
end

app/views/email_extension/messages/email.html.haml
%h1 Send email
= simple_form_for(@message) do |f|
  = f.error :base
  = f.error_notification
  = f.input :from
  = f.input :to
  = f.input :subject
  = f.input :body, :as => :text
  %br
  = f.button :submit, "Send"

app/views/email_extension/messages/new.html.haml
%ul.breadcrumb
  %li
    = link_to 'Home', main_app.admin_root_path
    
  %li
    = link_to 'Extensions', main_app.admin_extensions_path
    
  %li
    = link_to 'Email Notifier', settings_path
    
  %li Send Email

.page-header
  %h1 Send Email

= simple_form_for(@message, :html => {class: 'form-horizontal'}) do |f|
  .form-inputs
    = f.error :base
    = f.error_notification
    = f.input :from
    = f.input :to
    = f.input :subject
    = f.input :body, :as => :text, input_html: {rows: 5}
  .form-actions
    = f.button :submit, "Send", {class: 'btn btn-primary'}
    = link_to 'Cancel', settings_path, class: 'btn btn-link'

app/views/email_extension/settings/index.html.haml
%ul.breadcrumb
  %li
    = link_to 'Home', main_app.admin_root_path
    
  %li
    = link_to 'Extensions', main_app.admin_extensions_path
    
  %li.active Email Notifier

.page-header
  %h1 Email Notifier
  %p Manage the email extension.

= link_to new_message_path, class: 'btn btn-lg btn-primary' do
  Send Email
  %i.fa.fa-arrow-circle-o-right

%hr

= paginate @messages
- if @messages.size == 0
  .alert No email messages yet.
- else
  %table.table.table-striped
    %thead
      %tr
        %th From
        %th To
        %th Subject
        %th Time
    %tbody
      - @messages.each do |message|
        %tr
          %td.ap-mono= message.from
          %td.ap-mono= message.to
          %td= message.subject
          %td.ap-mono= message.updated_at

app/views/layouts/email_extension/application.html.haml
!!!
%html
  %head
    %title EmailExtension
    = stylesheet_link_tag    "email_extension/application", :media => "all"
    = javascript_include_tag "email_extension/application"
    = stylesheet_link_tag 'admin'
    = csrf_meta_tags
  %body
    = yield